
package br.ufc.mdcc.hpcshelf.backendservices.pyws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "BackEndService", targetNamespace = "http://www.mdcc.ufc.br/hpcshelf/backend/", wsdlLocation = "http://localhost:8000/backendservices/wsdl")
public class BackEndServicePyWS
    extends Service
{

    private final static URL BACKENDSERVICE_WSDL_LOCATION;
    private final static WebServiceException BACKENDSERVICE_EXCEPTION;
    private final static QName BACKENDSERVICE_QNAME = new QName("http://www.mdcc.ufc.br/hpcshelf/backend/", "BackEndService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8000/backendservices/wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        BACKENDSERVICE_WSDL_LOCATION = url;
        BACKENDSERVICE_EXCEPTION = e;
    }

    public BackEndServicePyWS() {
        super(__getWsdlLocation(), BACKENDSERVICE_QNAME);
    }

    public BackEndServicePyWS(WebServiceFeature... features) {
        super(__getWsdlLocation(), BACKENDSERVICE_QNAME, features);
    }

    public BackEndServicePyWS(URL wsdlLocation) {
        super(wsdlLocation, BACKENDSERVICE_QNAME);
    }

    public BackEndServicePyWS(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, BACKENDSERVICE_QNAME, features);
    }

    public BackEndServicePyWS(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BackEndServicePyWS(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns BackEndPortType
     */
    @WebEndpoint(name = "BackEndPort")
    public BackEndPortType getBackEndPort() {
        return super.getPort(new QName("http://www.mdcc.ufc.br/hpcshelf/backend/", "BackEndPort"), BackEndPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BackEndPortType
     */
    @WebEndpoint(name = "BackEndPort")
    public BackEndPortType getBackEndPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.mdcc.ufc.br/hpcshelf/backend/", "BackEndPort"), BackEndPortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (BACKENDSERVICE_EXCEPTION!= null) {
            throw BACKENDSERVICE_EXCEPTION;
        }
        return BACKENDSERVICE_WSDL_LOCATION;
    }

}
